PREFIX wd: <https://medievalcharterskg.wikibase.cloud/entity/>
PREFIX wdt: <https://medievalcharterskg.wikibase.cloud/prop/direct/>

SELECT ?personLabel ?personId (COUNT(?role) AS ?numberOfAppearances) WHERE {
  ?activity wdt:P3 wd:Q14 ;
            ?role ?person.
  ?person wdt:P3 wd:Q16;
          wdt:P1 ?personId.
  
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" .
  }
}
GROUP BY ?personLabel ?personId
ORDER BY DESC(?numberOfAppearances)
