PREFIX wd: <https://medievalcharterskg.wikibase.cloud/entity/>
PREFIX wdt: <https://medievalcharterskg.wikibase.cloud/prop/direct/>

SELECT ?class (COUNT(?entity) AS ?numberOfEntities)  WHERE {
  ?entity wdt:P3 ?class .
  
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" .
    ?paymentType rdfs:label ?paymentTypeLabel .
  }
}
GROUP BY ?class
ORDER BY DESC(?numberOfEntities)
