#Counts all statements that only have a given property as reference
PREFIX p: <https://medievalcharterskg.wikibase.cloud/prop/>
PREFIX pr: <https://medievalcharterskg.wikibase.cloud/prop/reference/>
PREFIX ps: <https://medievalcharterskg.wikibase.cloud/prop/statement/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX wbref: <http://wikiba.se/ontology#reference>

SELECT (COUNT(DISTINCT ?statementNode) AS ?countStatementsOnlyPRef)
WHERE {
  ?statementNode prov:wasDerivedFrom ?referenceNode .

  ?statementNode ?psPredicate ?value .
  FILTER(STRSTARTS(STR(?psPredicate), STR(ps:)))

  FILTER EXISTS {
    ?statementNode prov:wasDerivedFrom ?refWithP .
    ?refWithP pr:{ref_prop} ?valueP .
  }

  # Filter: Ensure there is NO reference property for this statement
  # that is NOT P AND NOT a standard allowed reference property
  FILTER NOT EXISTS {
    ?statementNode prov:wasDerivedFrom ?someRef .
    ?someRef ?otherProperty ?otherValue .
    FILTER(?otherProperty != pr:{ref_prop} &&
           ?otherProperty != wbref:referenceRetrievalDate &&
           ?otherProperty != wbref:referenceURL)
  }
}
