#Counts all entities that are instances of a given class with percentage
PREFIX wd: <https://medievalcharterskg.wikibase.cloud/entity/>
PREFIX wdt: <https://medievalcharterskg.wikibase.cloud/prop/direct/>

SELECT ?classLabel (COUNT(?entity) AS ?numberOfEntities) 
       (100 * COUNT(?entity) / ?total AS ?percentage)
WHERE {
  {
    SELECT (COUNT(DISTINCT ?allEntities) AS ?total) WHERE {
      ?allEntities wdt:P3 ?anyClass .
    }
  }
  
  ?entity wdt:P3 ?class .
  
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" .
  }
}
GROUP BY ?classLabel ?total
ORDER BY DESC(?numberOfEntities)
