SELECT ?item ?name
WHERE
{
  ?item p:P31 ?ps .
  ?ps ps:P31 ?subclass .
  ?subclass (wdt:P279*) wd:Q101352 .
  ?ps pq:P642 ?name .
  ?item wdt:P407 wd:{{language}} .
  ?name wdt:P31/wdt:P279* wd:Q202444
}
